//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bulk_Mailing {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bulk_Mailing.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Toplu Mail Atma Programı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string _maintext {
            get {
                return ResourceManager.GetString("_maintext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program Hakkında benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string _programmeinfo {
            get {
                return ResourceManager.GetString("_programmeinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   insert into veri(isim,mail) values (@isim,@mail) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string addveri {
            get {
                return ResourceManager.GetString("addveri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya / Dosyalar Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btn_addfolder {
            get {
                return ResourceManager.GetString("btn_addfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kişilerin Veri Excel&apos;ini Seç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btn_getmaillist {
            get {
                return ResourceManager.GetString("btn_getmaillist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kişilere Mail Göndermeyi Başlat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btn_sendmail {
            get {
                return ResourceManager.GetString("btn_sendmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Adresi Onaylıyorum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string changingaddress_btn_acceptnewaddress {
            get {
                return ResourceManager.GetString("changingaddress_btn_acceptnewaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adreste Düzenleme Yapabilmek için Doğrulama Kodu Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string changingaddress_btn_sendingcode {
            get {
                return ResourceManager.GetString("changingaddress_btn_sendingcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kodu Onaylıyorum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string changingaddress_btn_verifycode {
            get {
                return ResourceManager.GetString("changingaddress_btn_verifycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mevcut Adres benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string changingaddress_lbl_title {
            get {
                return ResourceManager.GetString("changingaddress_lbl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Adresi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string changingaddress_lbl_titleaddress {
            get {
                return ResourceManager.GetString("changingaddress_lbl_titleaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kod: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string changingaddress_lbl_titlecode {
            get {
                return ResourceManager.GetString("changingaddress_lbl_titlecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı mail adresi bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string couldntfindmailaddress {
            get {
                return ResourceManager.GetString("couldntfindmailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yüklü bir dosya bulunmamaktadır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string currentcondition {
            get {
                return ResourceManager.GetString("currentcondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///    adet dosya gönderilmek üzere ek kısmına eklenmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string currentcondition2 {
            get {
                return ResourceManager.GetString("currentcondition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   delete from veri where mail=@mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string deletemail {
            get {
                return ResourceManager.GetString("deletemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   delete from veri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string deleteveri {
            get {
                return ResourceManager.GetString("deleteveri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en-US benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EN benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email gönderme işlemi başlatılmadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string errormail {
            get {
                return ResourceManager.GetString("errormail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlatılmayan İşlem benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string errorprocess {
            get {
                return ResourceManager.GetString("errorprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel Dosyası |*.xlsx| Excel Dosyası|*.xls benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string excelfilter {
            get {
                return ResourceManager.GetString("excelfilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Veri Excel&apos;ini seçiniz... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string exceltitle {
            get {
                return ResourceManager.GetString("exceltitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şekil - 1 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string figure {
            get {
                return ResourceManager.GetString("figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string headeremail {
            get {
                return ResourceManager.GetString("headeremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İsim ve Soyisim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string headernameandsurname {
            get {
                return ResourceManager.GetString("headernameandsurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı Mail Adreslerini Gizle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hideerrorlist {
            get {
                return ResourceManager.GetString("hideerrorlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hacettepe Üniversitesi Psikoloji Topluluğu (HÜPT) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hupt_title {
            get {
                return ResourceManager.GetString("hupt_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merhaba Sevgili  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hupt_title3 {
            get {
                return ResourceManager.GetString("hupt_title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilgilendirme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ekteki Dosya / Dosyalar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_currentfolder {
            get {
                return ResourceManager.GetString("lbl_currentfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kod Gönderen Mail Adresini Düzenlemek için Tıklayınız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_editingaddress {
            get {
                return ResourceManager.GetString("lbl_editingaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı Mail Adresleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_errormail {
            get {
                return ResourceManager.GetString("lbl_errormail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **Hatalı olan mail adresleri otomatik olarak listeden kaldırılacaktır.** benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_errormailshow {
            get {
                return ResourceManager.GetString("lbl_errormailshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program Hakkında Detaylı Bilgi Almak için Tıklayınız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_programinfo {
            get {
                return ResourceManager.GetString("lbl_programinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mailler Gönderiliyor... Lütfen Programı Kapatmayınız... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_sendcodeinfo {
            get {
                return ResourceManager.GetString("lbl_sendcodeinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı Mail Adreslerini Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_showerrorlist {
            get {
                return ResourceManager.GetString("lbl_showerrorlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tüm Mailler Başarı Bir Şekilde Gönderildi :)) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblinfowithload {
            get {
                return ResourceManager.GetString("lblinfowithload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * Bu program Hacettepe Üniversitesi Psikoloji Topluluğu&apos;nun toplu mail işlemlerini düzenlemek amacıyla oluşturulmuştur.
        /// 
        ///* Katılımcıları içeren excel dosyanızı programa yüklemeden önce ilgili excel dosyanıza girerek excel dosyanızın &quot;Şekil - 1&quot;deki gibi olmasını sağlamalısınız. İsimler A sütununda Mailler B sütununda olmalı ve geri kalan sütunlarda herhangi bir veri olmamalıdır. Program, A ve B sütunlarından kişilerin bilgilerini alacak şekilde tasarlanmıştır.
        ///
        ///* Mail Gönderimi: Veri girişini tamamladı [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblprograminfo {
            get {
                return ResourceManager.GetString("lblprograminfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mevcut Dosyaların Toplam Boyutu: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbltotalfile {
            get {
                return ResourceManager.GetString("lbltotalfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Gönderilecek Toplam Kişi Sayısı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbltotalpeople {
            get {
                return ResourceManager.GetString("lbltotalpeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **Dosya boyut sınırı olarak &quot;20 MB&quot; belirlenmiştir, 20 MB&apos;ı geçmediği sürece birden fazla dosya eklenebilir.** benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblwarningaboutsize {
            get {
                return ResourceManager.GetString("lblwarningaboutsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı mail adresi bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lst_errorlist1 {
            get {
                return ResourceManager.GetString("lst_errorlist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 adet hatalı mail adresi çıkarıldı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lst_errorlist2 {
            get {
                return ResourceManager.GetString("lst_errorlist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    adet hatalı mail adresleri çıkarıldı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lst_errorlist3 {
            get {
                return ResourceManager.GetString("lst_errorlist3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mail_ {
            get {
                return ResourceManager.GetString("mail_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yüklemiş olduğunuz excelde herhangi bir veri bulunamadı ya da veriler içinden geçerli olan herhangi bir doğrulama kodu bulunamadı. Lütfen excel dosyanızın içinde verilerin olduğundan ve var olan doğrulama kodlarının doğru olduğundan emin olunuz ve ardından tekrar deneyiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mb_error {
            get {
                return ResourceManager.GetString("mb_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hata benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mb_hata {
            get {
                return ResourceManager.GetString("mb_hata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Katılımcılara toplu bir şekilde e-mail göndermek istediğinize emin misiniz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mbbulkmail {
            get {
                return ResourceManager.GetString("mbbulkmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;Hata:\n\n&quot; + ex.ToString() + &quot;\n\nAlternatif Öneriler\n\n1. Yüklemeye çalıştığınız dosyaları .rar haline getirip öyle yüklemeyi deneyebilirsiniz. \n\n2. Google, maillerde gönderilebilecek dosya boyutunu azaltmış olabilir. Daha az boyutlu bir biçimde dosyalarınızı yeniden yükleyebilirsiniz.&quot; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mbcatchmessage {
            get {
                return ResourceManager.GetString("mbcatchmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Taslağı Kontrolü benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mbcontroltitle {
            get {
                return ResourceManager.GetString("mbcontroltitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Herhangi bir veri girişi bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mberrornodataentry {
            get {
                return ResourceManager.GetString("mberrornodataentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yüklemeye çalıştığınız excel dosyasını lütfen kapatınız. Açık olan excel dosyanızı kapattıktan sonra programa veri girişini yapmayı lütfen tekrar deneyiniz. \n\nEk Bilgi: Hem herhangi bir programda hem de bilgisayarda eş zamanlı olarak aynı excel dosyası çalıştırılamaz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mberroropenexcel {
            get {
                return ResourceManager.GetString("mberroropenexcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen daha önceden eklemiş olduğunuz dosyaları tekrardan eklemeyiniz. Aynı dosyayı birden fazla kez ekleme girişiminiz program tarafından silinmiştir. Aynısını tekrardan eklemeye çalıştığınız mevcut dosyanın ismi:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mberrorsameexcelfile {
            get {
                return ResourceManager.GetString("mberrorsameexcelfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Boyutu Hatası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mberrorsize {
            get {
                return ResourceManager.GetString("mberrorsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yüklemiş olduğunuz excelde herhangi bir veri bulunamadı ya da veriler içinden geçerli olan herhangi bir mail adresi bulunamadı. Lütfen excel dosyanızın içinde verilerin olduğundan ve var olan mail adreslerinin doğru olduğundan emin olunuz ve ardından tekrar deneyiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mberrorwrongexcelfile {
            get {
                return ResourceManager.GetString("mberrorwrongexcelfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplam dosya boyutu 20 MB&apos;ı aşıyor. Lütfen seçtiğiniz dosyaların toplam 20 MB&apos;ı aşmadığından emin olunuz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mbfilesizeerror {
            get {
                return ResourceManager.GetString("mbfilesizeerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen tüm kutucukları doldurunuz! Doldurmanız gereken kutucukları kutucukların üstündeki yazıdan görebilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mbfill {
            get {
                return ResourceManager.GetString("mbfill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   e-mail gönderme işlemi başlatılmadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mbnotstart {
            get {
                return ResourceManager.GetString("mbnotstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Herhangi bir işlem yapılmadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messagecancel {
            get {
                return ResourceManager.GetString("messagecancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğrulama Kodu Onayı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messageconfirmcode {
            get {
                return ResourceManager.GetString("messageconfirmcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı doğrulama kodu girildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messageerrorcode {
            get {
                return ResourceManager.GetString("messageerrorcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adres Düzenleme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messagemailto {
            get {
                return ResourceManager.GetString("messagemailto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğrulama Kodu Gönderimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messagesendingcode {
            get {
                return ResourceManager.GetString("messagesendingcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Değişiklik başarıyla kaydedildi. Doğrulama kodları bundan sonra  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messagesuccesspart1 {
            get {
                return ResourceManager.GetString("messagesuccesspart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    adresinden gönderilecektir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messagesuccesspart2 {
            get {
                return ResourceManager.GetString("messagesuccesspart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem Başarılı. Lütfen size gönderilen doğrulama kodunu aktif olmuş olan kutucuğa yazınız ve onaylayınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messagesuccesssending {
            get {
                return ResourceManager.GetString("messagesuccesssending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem Başarılı. Hesapta düzenleme işlemlerinizi yapmaya başlayabilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messagesuccessverify {
            get {
                return ResourceManager.GetString("messagesuccessverify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlemi Başlatmak İstediğinize Emin Misiniz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messsagestart {
            get {
                return ResourceManager.GetString("messsagestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   isim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @isim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string name_ {
            get {
                return ResourceManager.GetString("name_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provider=Microsoft.ACE.OLEDB.12.0;Data Source=veri.accdb;Persist Security Info=True benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string oledbconveri {
            get {
                return ResourceManager.GetString("oledbconveri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select * from veri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string selectveri {
            get {
                return ResourceManager.GetString("selectveri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı Mail Adreslerini Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string showerrorlist {
            get {
                return ResourceManager.GetString("showerrorlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   smtp.gmail.com benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string smtp {
            get {
                return ResourceManager.GetString("smtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ----------------------- benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string symbol {
            get {
                return ResourceManager.GetString("symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///     (...),  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string symbol2 {
            get {
                return ResourceManager.GetString("symbol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %10 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tenpercentage {
            get {
                return ResourceManager.GetString("tenpercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tr-TR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tr {
            get {
                return ResourceManager.GetString("tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string turkce {
            get {
                return ResourceManager.GetString("turkce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ekteki Dosyalar:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string txt_attachedfile {
            get {
                return ResourceManager.GetString("txt_attachedfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şu an için yüklü bir dosya bulunmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string txt_filecontrol {
            get {
                return ResourceManager.GetString("txt_filecontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hitap:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string txt_font_appeal {
            get {
                return ResourceManager.GetString("txt_font_appeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail İçeriği:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string txt_font_content {
            get {
                return ResourceManager.GetString("txt_font_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Başlığı:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string txt_font_title {
            get {
                return ResourceManager.GetString("txt_font_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hitap Şeklinizi Giriniz... (Ör: Merhaba Sevgili) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string txtappeal {
            get {
                return ResourceManager.GetString("txtappeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail İçeriğini Giriniz... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string txtcontent {
            get {
                return ResourceManager.GetString("txtcontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Başlığını Giriniz... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string txttitle {
            get {
                return ResourceManager.GetString("txttitle", resourceCulture);
            }
        }
    }
}
